# database/db_core.py
# ================================================================
# این فایل به عنوان یک لایه سازگاری (Compatibility Layer) عمل می‌کند
# تا کدهای قدیمی که از 'from database.db_core import ...' استفاده می‌کنند،
# همچنان کار کنند.
# ================================================================
# توجه: برای جلوگیری از خطاهای import دوری (circular import)،
# این فایل فقط از ماژول‌های سطح پایین import می‌کند که وابستگی متقابل ندارند.
# ماژول‌های db_questions, db_orders, db_users, db_stats, db_logs, db_versioning
# به‌طور مستقیم از db_connection import می‌کنند و در این فایل import نمی‌شوند.
# ================================================================

from .db_connection import (
    get_db_connection,
    DB_NAME,
    init_db,
    add_validation_columns_if_not_exists,
    add_order_columns_if_not_exists,
    create_order_logs_table,
    add_columns_if_not_exists,
    add_price_columns_if_not_exists,
    add_user_block_columns_if_not_exists,
    create_question_templates_table,
)

from .db_categories import (
    add_category,
    get_category_by_location,
    get_all_categories,
    get_all_categories_admin,
    get_categories_with_buttons,
    get_category_by_id,
    update_category,
    delete_category,
    get_category_columns,
)

from .db_buttons import (
    add_button,
    get_buttons_by_location,
    get_buttons_by_category,
    get_buttons_by_category_for_admin,
    get_buttons_by_parent,
    get_all_buttons,
    get_button_by_callback,
    get_button_by_id,
    update_button,
    delete_button,
    delete_duplicate_submenus,
    get_all_submenus,
    get_button_columns,
)

from .db_admins import (
    is_admin,
    add_admin,
    remove_admin,
    get_all_admins,
    update_admin_role,
    toggle_admin_status,
    get_admin_stats,
    search_admins,
)

from .db_columns import (
    get_default_menu_columns,
    get_category_columns,
    get_button_columns,
    get_effective_columns,
    set_default_menu_columns,
    set_category_columns,
    set_button_columns,
    get_columns_info,
)

from .db_orders import (
    save_user_answer,
    get_user_answers,
    save_dynamic_order,
    get_dynamic_orders,
    get_dynamic_order_by_id,
    set_setting,
    get_setting,
    get_all_settings,
    add_order_log,
    update_order_status,
    delete_order,
    search_orders,
    get_order_stats,
    add_order_note,
    get_order_logs,
    get_user_order_stats,
    get_button_price_info,
    update_button_price,
    update_reminder_time,
    get_orders_for_reminder,
)

from .db_users import (
    upsert_user,
    get_user,
    get_all_users,
    get_total_users,
    get_active_users,
    get_user_orders_count,
    get_user_total_payment,
    get_users_with_stats,
    search_users,
    block_user,
    unblock_user,
    is_user_blocked,
    get_blocked_users,
    get_blocked_count,
    update_user_role,
    get_user_role,
    get_users_by_role,
    get_user_by_username,
    update_user_language,
    update_user_timezone,
    get_recent_users,
    get_users_with_filter,
    get_users_with_filter_count,
)

from .db_stats import (
    log_button_action,
    log_button_click,
    log_form_start,
    log_order_paid,
    get_button_stats,
    get_top_buttons,
    get_dashboard_stats,
    get_revenue_by_period,
    get_button_stats_by_date,
    get_top_users,
    get_button_stats_with_filter,
    get_advanced_stats,
    get_advanced_stats_aggregated,
)

from .db_logs import (
    log_error,
    get_error_logs,
    get_error_log_by_id,
    get_total_errors,
    get_error_types_with_count,
    mark_error_as_resolved,
    mark_error_as_unresolved,
    delete_error_logs,
    delete_error_log_by_id,
    clear_all_error_logs,
    get_error_stats,
    get_errors_by_user,
    get_errors_by_chat,
    get_error_count_by_type,
    get_recent_errors,
    get_error_report,
    clean_error_logs_with_retention,
)

from .db_versioning import (
    save_button_version,
    get_button_versions,
    get_button_version,
    get_latest_version,
    get_total_versions,
    restore_button_version,
    delete_button_version,
    delete_old_versions,
)

from .db_questions import (
    add_question,
    get_questions_by_button,
    get_question_by_id,
    get_previous_questions,
    update_question,
    delete_question,
    delete_questions_by_button,
    add_condition,
    get_conditions_by_question,
    get_condition_by_id,
    update_condition,
    delete_condition,
    delete_conditions_by_question,
    get_question_logic_operator,
    add_question_option,
    get_options_by_question,
    get_option_by_callback,
    delete_options_by_question,
    toggle_validation_feature,
    get_validation_settings,
    get_validation_status_summary,
    is_validation_feature_active,
    enable_all_validations,
    disable_all_validations,
    reset_validation_to_default,
    save_validation_profile,
    get_validation_profiles,
    get_validation_profile_by_name,
    apply_validation_profile,
)


__all__ = [
    # از db_connection
    'get_db_connection',
    'DB_NAME',
    'init_db',
    'add_validation_columns_if_not_exists',
    'add_order_columns_if_not_exists',
    'create_order_logs_table',
    'add_columns_if_not_exists',
    'add_price_columns_if_not_exists',
    'add_user_block_columns_if_not_exists',
    'create_question_templates_table',

    # از db_categories
    'add_category',
    'get_category_by_location',
    'get_all_categories',
    'get_all_categories_admin',
    'get_categories_with_buttons',
    'get_category_by_id',
    'update_category',
    'delete_category',
    'get_category_columns',

    # از db_buttons
    'add_button',
    'get_buttons_by_location',
    'get_buttons_by_category',
    'get_buttons_by_category_for_admin',
    'get_buttons_by_parent',
    'get_all_buttons',
    'get_button_by_callback',
    'get_button_by_id',
    'update_button',
    'delete_button',
    'delete_duplicate_submenus',
    'get_all_submenus',
    'get_button_columns',

    # از db_admins
    'is_admin',
    'add_admin',
    'remove_admin',
    'get_all_admins',
    'update_admin_role',
    'toggle_admin_status',
    'get_admin_stats',
    'search_admins',

    # از db_columns
    'get_default_menu_columns',
    'get_category_columns',
    'get_button_columns',
    'get_effective_columns',
    'set_default_menu_columns',
    'set_category_columns',
    'set_button_columns',
    'get_columns_info',

    # از db_orders
    'save_user_answer',
    'get_user_answers',
    'save_dynamic_order',
    'get_dynamic_orders',
    'get_dynamic_order_by_id',
    'set_setting',
    'get_setting',
    'get_all_settings',
    'add_order_log',
    'update_order_status',
    'delete_order',
    'search_orders',
    'get_order_stats',
    'add_order_note',
    'get_order_logs',
    'get_user_order_stats',
    'get_button_price_info',
    'update_button_price',
    'update_reminder_time',
    'get_orders_for_reminder',

    # از db_users
    'upsert_user',
    'get_user',
    'get_all_users',
    'get_total_users',
    'get_active_users',
    'get_user_orders_count',
    'get_user_total_payment',
    'get_users_with_stats',
    'search_users',
    'block_user',
    'unblock_user',
    'is_user_blocked',
    'get_blocked_users',
    'get_blocked_count',
    'update_user_role',
    'get_user_role',
    'get_users_by_role',
    'get_user_by_username',
    'update_user_language',
    'update_user_timezone',
    'get_recent_users',
    'get_users_with_filter',
    'get_users_with_filter_count',

    # از db_stats
    'log_button_action',
    'log_button_click',
    'log_form_start',
    'log_order_paid',
    'get_button_stats',
    'get_top_buttons',
    'get_dashboard_stats',
    'get_revenue_by_period',
    'get_button_stats_by_date',
    'get_top_users',
    'get_button_stats_with_filter',
    'get_advanced_stats',
    'get_advanced_stats_aggregated',

    # از db_logs
    'log_error',
    'get_error_logs',
    'get_error_log_by_id',
    'get_total_errors',
    'get_error_types_with_count',
    'mark_error_as_resolved',
    'mark_error_as_unresolved',
    'delete_error_logs',
    'delete_error_log_by_id',
    'clear_all_error_logs',
    'get_error_stats',
    'get_errors_by_user',
    'get_errors_by_chat',
    'get_error_count_by_type',
    'get_recent_errors',
    'get_error_report',
    'clean_error_logs_with_retention',

    # از db_versioning
    'save_button_version',
    'get_button_versions',
    'get_button_version',
    'get_latest_version',
    'get_total_versions',
    'restore_button_version',
    'delete_button_version',
    'delete_old_versions',

    # از db_questions
    'add_question',
    'get_questions_by_button',
    'get_question_by_id',
    'get_previous_questions',
    'update_question',
    'delete_question',
    'delete_questions_by_button',
    'add_condition',
    'get_conditions_by_question',
    'get_condition_by_id',
    'update_condition',
    'delete_condition',
    'delete_conditions_by_question',
    'get_question_logic_operator',
    'add_question_option',
    'get_options_by_question',
    'get_option_by_callback',
    'delete_options_by_question',
    'toggle_validation_feature',
    'get_validation_settings',
    'get_validation_status_summary',
    'is_validation_feature_active',
    'enable_all_validations',
    'disable_all_validations',
    'reset_validation_to_default',
    'save_validation_profile',
    'get_validation_profiles',
    'get_validation_profile_by_name',
    'apply_validation_profile',
]